### PR TITLE
Fix null exception and throw a FileNotFoundException if xml file is neve...

### LINKED ISSUE #44: No check of the configuration file existance in ServiceDescriptor initialization
Reproduction steps:
* Launch winsw in a folder without ${EXECUTABLE_NAME}.xml

Log:
> ..\tmp>winsw.exe install 
> System.ArgumentNullException: Value cannot be null.
> Parameter name: path1
>   at System.IO.Path.Combine(String path1, String path2)
>   at winsw.ServiceDescriptor..ctor()
>   at winsw.WrapperService.Run(String[] _args)
>   at winsw.WrapperService.Main(String[] args)

### PR DESCRIPTION
**Pull request by carpnick**
...r found

Fixes #44

### CODE REVIEW

File: ServiceDescriptor.cs [hunk 1]
```diff
@@ -45,18 +45,24 @@ public ServiceDescriptor()
...
+            DirectoryInfo d = new DirectoryInfo(Path.GetDirectoryName(p));
             while (true)
             {
-                p = Path.GetDirectoryName(p);
-                if (File.Exists(Path.Combine(p, baseName + ".xml")))
+                if (File.Exists(Path.Combine(d.FullName, baseName + ".xml")))
                     break;
+
+                if (d.Parent == null)
+                    throw new FileNotFoundException("Unable to locate "+baseName+".xml file within executable directory or any parents");
```
Comment (oleg-nenashev) [inline ServiceDescriptor.cs]: The message is incorrect.
The code searches across all upper directories. No idea why it is required, but seems this behavior should be retained.

Comment (carpnick) [inline ServiceDescriptor.cs]: This is using your same behavior but getting rid of your null issue.

The loop first checks for the file in directory.fullname with the basename, and if it doesnt exist, the directoryinfo object parent property returns null if you have searched up to C:\

See https://msdn.microsoft.com/en-us/library/system.io.directoryinfo.parent(v=vs.80).aspx

Basically your loop still redefines your string directory going from directory to directory.  But there is a potential you could search to c:\, still not find the xml file.  This is the root cause of your current null issue.  If you try to  find DirectoryName of C:\ you get null

Comment (oleg-nenashev) [inline ServiceDescriptor.cs]: Sorry. My message was about the error message only, but I have not read the entire message 
"or any parents" was not visible in GitHub code viewer (and I have not noticed a scrollbar)
