### PR TITLE
Treat ERROR_SERVICE_CANNOT_ACCEPT_CTRL as success for stop command

### LINKED ISSUE #309: 'winsw stop' does not handle already stopped service very well
When winsw (WinSW 2.1.2.0) executes a stop, and the service have status stoped an error is thrown:

`2019-04-08 02:44:37,095 INFO  - Stopping the service with id 'fingridcon'
2019-04-08 02:44:37,126 FATAL - WMI Operation failure: ServiceCannotAcceptControl
WMI.WmiException: ServiceCannotAcceptControl
   at WMI.WmiRoot.BaseHandler.CheckError(ManagementBaseObject result)
   at WMI.WmiRoot.InstanceHandler.Invoke(Object proxy, MethodInfo method, Object[] args)
   at WMI.Win32ServiceProxy.StopService()
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)
WMI.WmiException: ServiceCannotAcceptControl
   at WMI.WmiRoot.BaseHandler.CheckError(ManagementBaseObject result)
   at WMI.WmiRoot.InstanceHandler.Invoke(Object proxy, MethodInfo method, Object[] args)
   at WMI.Win32ServiceProxy.StopService()
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)`

Command returns ERRORLEVEL  5 in CMD. 

Steps to reproduce:
    Install winsw service (fingridcon.exe install).
    Stop the service (fingridcon.exe stop).
    Stop the service (fingridcon.exe stop).

A simple mesage:
    INFO  - Service with id 'fingridcon' is already stopped 
and a ERRORLEVEL 0 was expected.

### PR DESCRIPTION
**Pull request by NextTurn**
Closes #309 

The corresponding Windows API `ControlService` will return `ERROR_SERVICE_NOT_ACTIVE` instead.

### CODE REVIEW

File: src/Core/ServiceWrapper/Main.cs [hunk 1]
```diff
@@ -679,7 +679,18 @@ public static void Run(string[] _args, ServiceDescriptor? descriptor = null)
...
+                    try
+                    {
+                        s.StopService();
+                    }
+                    catch (WmiException e)
+                    {
+                        if (e.ErrorCode != ReturnValue.ServiceCannotAcceptControl)
+                        {
+                            throw;
+                        }
```
Comment (oleg-nenashev) [inline src/Core/ServiceWrapper/Main.cs]: Add some logging otherwise?

**Comment by oleg-nenashev** [comment]
W.r.t. this PR and #385 , my personal preference would be to keep the most aggressive failsafe behavior by default, and to allow ignoring particular states via flags. But it is rather a Unix way , I am open to inverting the behavior and using commands like `start!` and `stop!` for a failsafe behavior (or any SLI-friendly command)

**Comment by NextTurn** [comment]
Just FYI, PowerShell will ignore such errors silently.
